### ISSUE TITLE
SocialElement for Facebook and Twitter is broken

### ISSUE THREAD

**Issue by ceefour** [mautic/plugin-grapesjs-builder#63] opened 2021-02-24 06:28 UTC
## How to Reproduce

1. Create Social Group with one or two SocialElement's
2. With Facebook, set href: https://www.facebook.com/miluvapp/
3. With Twitter, set href: https://twitter.com/miluvapp

## What should happen

These link to the exact hrefs as entered.

## What actually happened

1. Facebok link goes to: https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/miluvapp/
2. Twitter link goes to: https://twitter.com/home?status=https://twitter.com/miluvapp

## What should be fixed

When using "href", SocialElement should output it as-is.

However, if it's for sharing, there should be additional option (that is mutually exclusive with `href`), for example for Facebook "shared URL", and for Twitter "status" (because it's **not** a href anyway).

## Version

Mautic 3.3.0

**Comment by RCheesley** [comment] 2021-02-24 07:22
Thanks for reporting this, would you be able to dig into the code and make a PR to address this?

**Comment by RCheesley** [comment] 2021-03-28 12:47
Hi @ceefour thanks for reporting this.

Actually this is the default behaviour for the social block in GrapesJS. There is a question in their issue queue over at https://github.com/artf/grapesjs-mjml/issues/238 - maybe you could add your thoughts there.

Will close this issue as this is the expected behaviour and not a bug with our implementation of GrapesJS - suggest you just use a hyperlinked icon if you wish to have a link to your profiles/pages.

**Closed by RCheesley** 2021-03-28 12:47 UTC
Labels: bug
