### ISSUE TITLE
Text block disappears and becomes box and cant edit anymore

### ISSUE THREAD

**Issue by weismannweb** [mautic/plugin-grapesjs-builder#20] opened 2020-09-13 19:39 UTC
Hi,

So using grape js plugin with Mautic 3.1.0 I get an issue where an editable text block became a non editable block and the text is then had coded and cannot be edited.

https://drive.google.com/file/d/1RZ7qOX-rLs3rXmu1KxGQHr86OvUmqTzP/view

[rgabeforetemplate.txt](https://github.com/Webmecanik/plugin-grapesjs-builder/files/5214998/rgabeforetemplate.txt)
[rgatemplate.txt](https://github.com/Webmecanik/plugin-grapesjs-builder/files/5214999/rgatemplate.txt)

**Comment by RCheesley** [comment] 2021-02-14 00:03
Thanks for the video, that really helped! I tested with the current release and the latest Mautic and could not reproduce this, so am going to close the issue. If anyone else encounters it please shout and we can reopen!

**Closed by RCheesley** 2021-02-14 00:03 UTC
Labels: bug
