### ISSUE TITLE
Cloning MJML Template - Reverts template to HTML and locks editor

### ISSUE THREAD

**Issue by TornMarketing** [mautic/plugin-grapesjs-builder#56] opened 2021-02-16 04:58 UTC
Cloning MJML Template - Reverts template to HTML and locks editor

When you clone an existing MJML template using the Blank MJML code builder, the newly created template is converted to HTML and I suspect you are not able to edit the newly created template as it is trying to edit it as if its MJML as it is still utilising the MJML Blank code base template.

Recreation steps
1) Create / Save a MJML email using Blank MJML Code template
2) Clone exiting MJML Email
3) Edit newly created email

**Comment by kuzmany** [comment] 2021-04-23 20:18
I am not able to reproduce. 

@RCheesley can you test it?

**Comment by RCheesley** [comment] 2021-04-24 09:01
I tested both with the blank theme and with Brienz and was unable to reproduce this issue.

**Comment by kuzmany** [comment] 2021-04-24 17:10
Re-open. I found issue, If clone MJML, then in clone email is open HTML version of GrapesJs

**Comment by RCheesley** [comment] 2021-04-24 17:12
Ahhh, so it is still opening but it has reverted to HTML markup rather than MJML - sorry misunderstood the issue description!

**Comment by kuzmany** [comment] 2021-04-24 17:16
I will look on it today or tomorrow

**Comment by RCheesley** [comment] 2021-05-04 16:10
Issue resolved with #75

**Closed by RCheesley** 2021-05-04 16:10 UTC
